### ISSUE TITLE
Integrate with Sentry for error handling

### ISSUE THREAD

**Issue by oleast** [dotkom/bookingsystem#17]
[Sentry](https://sentry.io) is a way to log and organize all runtime exceptions and other unwanted behavior of an application. We use it in most of our software to know when things are not going as expected.

**Describe the solution you'd like**

I think it could be nice to integrate with Sentry in both the back-end and front-end of this application as-well.

Sentry has an [integration for Nodejs](https://docs.sentry.io/platforms/node/express/), which should work for the express server.

There is also an integration for the browser, and a specific [integration for Vue](https://docs.sentry.io/platforms/javascript/vue/)
The really nice part about this is that it will log exceptions happening in the client browser, and even the state of the relevant component, which can make debugging actual client errors a lot easier!

**Additional context**
Sentry needs a `dsn` (key) to authorize usage in production. This will have to be provided by someone with admin access to Sentry (Dotkom).

**Comment by ghost** [comment]
Nice, i'll take a look at Sentry when i'm done with the current issues.
